### ISSUE TITLE
GDKP Board - Buyer History 

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GDKPd-Classic#39] opened 2022-11-26 18:44 UTC
Adding this as a placeholder, but since we'll have the data should be easy enough to show total spent by any given player. This is great for people running GDKPs to know who the "whales" are.

**Comment by TannerShmoog** [comment] 2022-12-09 00:12
Dupe of #31

**Closed by TannerShmoog** 2022-12-09 00:12 UTC
Labels: Priority - 3 Average, Type - New Functionality
