### ISSUE TITLE
Auction Session History Viewer

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GDKPd-Classic#31] opened 2022-11-16 05:09 UTC
# Story

Need a way to see past raids, and export data about what dropped, what it sold for, and who bought it.

# Acceptance Criteria

* May be useful to have an "average item sold for" data.
* May be useful to know who the "whales" are so you can track your big spenders over time.
* Data Export : Loot Lists
* Data Export : Buyers

# Wireframes / Design Links

# Legacy Screenshots

**Comment by TannerShmoog** [comment] 2022-12-14 08:30
less detailed dupe of #38

**Closed by TannerShmoog** 2022-12-14 08:30 UTC
Labels: Priority - 3 Average, Type - New Functionality
